<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nouveau contact</title>
</head>
<body>
    <h1>Nouveau contact</h1>
    <form method="post">
        <div>
            <label for="contact-name">Nom</label>
            <input type="text" id="contact-name" name="name">
        </div>
        <button>Envoyer</button>
    </form>
</body>
</html>