<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon carnet d'adresse</title>
</head>
<body>
    <h1>Mon carnet d'adresse</h1>
    <p>Détail du contact <strong><?= htmlspecialchars($contact->name) ?></strong>.</p>
    <p><a href="/">Retour à l'accueil</a></p>
</body>
</html>
