<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon carnet d'adresse</title>
</head>
<body>
    <h1>Mon carnet d'adresse</h1>
    <ul>
    <?php foreach ($contacts as $contact): ?>
        <li><a href="/<?= $contact->id ?>"><?= $contact->name ?></a></li>
    <?php endforeach; ?>
    </ul>
</body>
</html>
